version: '2.0'
services:
  chatgpt-on-wechat:
    build:
      context: ./
      dockerfile: Dockerfile.alpine
    image: img-cow-role-human
    container_name: cr-cow-role-human
    environment:
      OPEN_AI_API_BASE: 'https://openai.ifree.love/v1'
      OPEN_AI_API_KEY: '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'
      OPEN_AI_PROXY: ''
      SINGLE_CHAT_PREFIX: ''
      SINGLE_CHAT_REPLY_PREFIX: ''
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT正式群","💪🏻真AI健身群 | 施瓦辛格"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: "False"
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
